name: GitHub Classroom Workflow
on:
  push:
    branches: [ master ]
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v2
      
      - name: Login in dockerhub
        uses: docker/login-action@v2
        with:
          username: outsidious
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build docker images
        run: |
          docker build ./v2/loyalty/ -t outsidious/dockerhub:loyalty
          docker build ./v2/payment/ -t outsidious/dockerhub:payment
          docker build ./v2/reservation/ -t outsidious/dockerhub:reservation
          docker build ./v2/gateway/ -t outsidious/dockerhub:gateway

      
      - name: Push docker images
        run: |
          docker push outsidious/dockerhub:loyalty
          docker push outsidious/dockerhub:payment
          docker push outsidious/dockerhub:reservation
          docker push outsidious/dockerhub:gateway


      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: v2/postman/collection.json
          environment: v2/postman/environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'

      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true

      - name: Github auto grader mark
        uses: Romanow/google-sheet-autograder-marker@v1.0
        with:
          google_token: ${{secrets.GOOGLE_API_KEY}}
          sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
          homework_number: 4
          user_column: 'D'
          column_offset: 'F'
          mark: "'+"