name: GitHub Classroom Workflow
on:
  push:
    branches: [ master ]
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v2
      
      #- name: Login container registry
      #  id: login-cr
      #  uses: yc-actions/yc-cr-login@v1
      #  with:
      #    yc-sa-json-credentials: ${{ secrets.YA__JSON_SERVICE_ACCAUNT }}

      - name: Build docker images
        run: |
          docker build ./v2/gateway/ -t gateway:v1.0
          docker build ./v2/loyalty/ -t loyalty:v1.0
          docker build ./v2/payment/ -t payment:v1.0
          docker build ./v2/reservation/ -t reservation:v1.0
      
      #- name: Push docker images
      #  run: |
      #    docker push gateway:v1.0
      #    docker push loyalty:v1.0
      #    docker push payment:v1.0
      #    docker push reservation:v1.0

      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: v2/postman/collection.json
          environment: v2/postman/environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'

      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true

      - name: Github auto grader mark
        uses: Romanow/google-sheet-autograder-marker@v1.0
        with:
          google_token: ${{secrets.GOOGLE_API_KEY}}
          sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
          homework_number: 4
          user_column: 'D'
          column_offset: 'F'
          mark: "'+"